# Generated by Django 3.1.4 on 2021-03-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20210301_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
